sudo: required # for setting hostname
addons:
  hostname: localhost #https://github.com/travis-ci/travis-ci/issues/5227
language: java
jdk:
  - openjdk11
  - oraclejdk9
  - openjdk10
  - openjdk8
notifications:
 